### PR TITLE
reconstructed if > else statements

### PR DESCRIPTION
**Pull request by cronlabspl**

### CODE REVIEW

**Comment by natanfelles** [comment]
Hello @cronlabspl !

Thanks for the PR. But we cannot add these updates.

The `require` expression produces a fatal error and halt the script. The `die` is not necessary.

**Comment by cronlabspl** [comment]
@natanfelles Whats preferred way to contact you in private? Have some suggestion to make

**Comment by natanfelles** [comment]
> @natanfelles Whats preferred way to contact you in private? Have some suggestion to make

Please, send email to natanfelles@gmail.com.

**Comment by natanfelles** [comment]
> @natanfelles Whats preferred way to contact you in private? Have some suggestion to make

Please, open a **confidential** issue at https://gitlab.com/aplus-framework/projects/app/-/issues

**Comment by cronlabspl** [comment]
@natanfelles sure thing. Will contact you tomorrow 👍

**Pull request closed without merging**
